update launcher to use new gda folder structure after moving config to git
for example
gda -> gda_versions/gda_master

gda_master	| client
			| config -> workspace_git/gda-dls-beamline-i11.git/i11
			| workspace
			| workspace_git

diff --git a/i11/bin/GDA_RemoteStart_Lin b/i11/bin/GDA_RemoteStart_Lin
--- a/i11/bin/GDA_RemoteStart_Lin
+++ b/i11/bin/GDA_RemoteStart_Lin
@@ -10,7 +10,13 @@ then
   echo "Please set BEAMLINE environment variable."
   exit 1
 fi
-
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot source /etc/profile.d/modules.sh"	
+	exit 1
+fi
 notify-send -t 10000 "GDA Remote Servers are starting..."
 
 echo "Kill all GDA Clients running locally"
diff --git a/i11/bin/GDA_StartClient b/i11/bin/GDA_StartClient
--- a/i11/bin/GDA_StartClient
+++ b/i11/bin/GDA_StartClient
@@ -3,7 +3,13 @@
 notify-send -t 10000 "GDA is starting..."
 
 . /$SOFTWAREFOLDER/$BEAMLINE/software/gda/$BEAMLINE-config/bin/gda_environment.sh
-
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot source /etc/profile.d/modules.sh"	
+	exit 1
+fi
 # Start log panel if not already started
 LOGPANEL=$(ps -ef | grep LogPanel | grep -v grep)
 if [ "X$LOGPANEL" == "X" ] ; then
@@ -16,12 +22,13 @@ fi
 lpoptions -d b.i11.cc2.col.1 -o job-sheets=none,none
 
 if [ -n "$JAVA_OPTS" ] ; then
-	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=128m $JAVA_OPTS"
+	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=128m -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/gdaclient.hprof $JAVA_OPTS"
 else
-	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=128m"
+	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=128m -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/gdaclient.hprof"
 fi
 
-`dirname $0`/gda client  $@ -x ../clients/main/live/client.xml
+`dirname $0`/gda_command client  $@ -x ../clients/main/live/client.xml
+
 
 if [ "X$LOGPANEL" == "X" ] ; then
 	sleep 5
diff --git a/i11/bin/GDA_StartLogPanel b/i11/bin/GDA_StartLogPanel
--- a/i11/bin/GDA_StartLogPanel
+++ b/i11/bin/GDA_StartLogPanel
@@ -1,6 +1,13 @@
 #!/bin/bash
 
 . "/$SOFTWAREFOLDER/$BEAMLINE/software/gda/$BEAMLINE-config/bin/gda_environment.sh"
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot scd ..ource /etc/profile.d/modules.sh"	
+	exit 1
+fi
 
 PORT_6790_USED=`ps -ef | grep gda.logPanel.logging.port=6790 | grep -v grep`
 PORT_6791_USED=`ps -ef | grep gda.logPanel.logging.port=6791 | grep -v grep`
@@ -29,6 +36,8 @@ else
 	export JAVA_OPTS=-Dgda.logPanel.logging.port=$PORT
 fi
 
+
+export JAVA_OPTS=-Dgda.logPanel.logging.port=$PORT $JAVA_OPTS
 echo "Staring GDA Log Panel locally"
-echo "`dirname $0`/gda logpanel --restart $@"
-`dirname $0`/gda logpanel --restart $@
+echo "`dirname $0`/gda_command logpanel --restart $@"
+`dirname $0`/gda_command logpanel --restart $@
diff --git a/i11/bin/GDA_StartRCP b/i11/bin/GDA_StartRCP
--- a/i11/bin/GDA_StartRCP
+++ b/i11/bin/GDA_StartRCP
@@ -9,6 +9,13 @@ fi
 notify-send -t 10000 "GDA RCP Client is starting..."
 
 . /$SOFTWAREFOLDER/$BEAMLINE/software/gda/$BEAMLINE-config/bin/gda_environment.sh
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot scd ..ource /etc/profile.d/modules.sh"	
+	exit 1
+fi
 
 # Start log panel if not already started
 LOGPANEL=$(ps -ef | grep LogPanel | grep -v grep)
@@ -22,12 +29,12 @@ fi
 lpoptions -d b.i11.cc2.col.1 -o job-sheets=none,none
 
 if [ -n "$JAVA_OPTS" ] ; then
-	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=256m -XX:MaxHeapFreeRatio=70 -XX:+DisableExplicitGC -XX:+UseGCOverheadLimit -XX:-UseParallelGC -XX:ParallelGCThreads=8 $JAVA_OPTS"
+	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=256m -XX:MaxHeapFreeRatio=70 -XX:+DisableExplicitGC -XX:+UseGCOverheadLimit -XX:-UseParallelGC -XX:ParallelGCThreads=8 -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/gdaclient.hprof $JAVA_OPTS"
 else
-	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=256m -XX:MaxHeapFreeRatio=70 -XX:+DisableExplicitGC -XX:+UseGCOverheadLimit -XX:-UseParallelGC -XX:ParallelGCThreads=8"
+	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=256m -XX:MaxHeapFreeRatio=70 -XX:+DisableExplicitGC -XX:+UseGCOverheadLimit -XX:-UseParallelGC -XX:ParallelGCThreads=8 -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/gdaclient.hprof"
 fi
 
-`dirname $0`/gda rcpclient --rcp_image=/$SOFTWAREFOLDER/$BEAMLINE/software/gda/client/gda-${BEAMLINE} --restart --debug --debugport=8003 $@
+`dirname $0`/gda_command rcpclient --rcp_image=/$SOFTWAREFOLDER/$BEAMLINE/software/gda/client/gda-${BEAMLINE} --restart $@ #--debug --debugport=8003 $@
 
 #To run the RCP client directly
 #/$SOFTWAREFOLDER/${BEAMLINE}/software/gda/client/gda-${BEAMLINE} $@ & 
diff --git a/i11/bin/GDA_StartServers b/i11/bin/GDA_StartServers
--- a/i11/bin/GDA_StartServers
+++ b/i11/bin/GDA_StartServers
@@ -1,4 +1,12 @@
 #!/bin/bash
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot source /etc/profile.d/modules.sh"	
+	exit 1
+fi
+
 `dirname $0`/gda nameserver --stop $@
 `dirname $0`/gda logserver --stop $@
 `dirname $0`/gda eventserver --stop $@
@@ -9,9 +17,9 @@
 `dirname $0`/gda eventserver $@
 
 if [ -n "$JAVA_OPTS" ] ; then
-	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=256m -XX:+DisableExplicitGC $JAVA_OPTS"
+	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=256m -XX:+DisableExplicitGC -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/gdaobjectserver.hprof $JAVA_OPTS"
 else
-	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=256m -XX:+DisableExplicitGC"
+	export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=256m -XX:+DisableExplicitGC -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/gdaobjectserver.hprof"
 fi
 
-`dirname $0`/gda objectserver  --smart --trace --debug -p 8001 --restart -v --mode=live $@
+`dirname $0`/gda_command objectserver  --smart --trace --debug -p 8001 --restart -v --mode=live $@
diff --git a/i11/bin/startgda b/i11/bin/startgda
--- a/i11/bin/startgda
+++ b/i11/bin/startgda
@@ -3,6 +3,13 @@
 ##This requires generation of ssh keys and copying the public key to the authorized_keys file in the server
 ##Please refer to the document howtoSSH.txt for key generation.
 ##To use this script change the key file path, user name and the server machine name
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot scd ..ource /etc/profile.d/modules.sh"	
+	exit 1
+fi
 
 zenity --title "Are you sure?" --question --text "Are you sure you want to restart the GDA servers?" --window-icon=question
 SURE=$?
@@ -18,7 +25,7 @@ SSHOPTS="-o StrictHostKeyChecking=no -o BatchMode=yes"
 
 ssh-keygen -R $BEAMLINE-control.diamond.ac.uk 2> /dev/null
 #sed -i -e "/$BEAMLINE-control/d" ~/.ssh/known_hosts
-ssh $SSHOPTS -i /$SOFTWAREFOLDER/${BEAMLINE}/software/gda/${BEAMLINE}-config/${BEAMLINE}ssh.key gda@${BEAMLINE}-control.diamond.ac.uk 
+ssh $SSHOPTS -i /$SOFTWAREFOLDER/${BEAMLINE}/software/gda/config/${BEAMLINE}ssh.key gda2@${BEAMLINE}-control.diamond.ac.uk 
 
 # Start log panel if not already started
 LOGPANEL=$(ps -ef | grep LogPanel | grep -v grep)
@@ -33,7 +40,7 @@ fi
 echo "Restarting the GDA Server, please wait..."
 echo "Keep this window open, and you will see a pop-up when the restart has completed"
 echo
-/$SOFTWAREFOLDER/$BEAMLINE/software/gda/mx-config/bin/lookForFile $SERVER_STARTUP_FILE
+/$SOFTWAREFOLDER/$BEAMLINE/software/gda/config/bin/lookForFile $SERVER_STARTUP_FILE
 
 zenity --title "Start the Client?" --question --text "The GDA servers have restarted. Click OK to start the GDA Client." --window-icon=question
 STARTCLIENT=$?
